export const PAYMENT_ADD_ITEM = "PAYMENT_ADD_ITEM";
export const PAYMENT_REMOVE_ITEM = "PAYMENT_REMOVE_ITEM";
export const PAYMENT_CLEAR_ITEMS = "PAYMENT_CLEAR_ITEMS";
export const PAYMENT_SAVE_SHIPPING_ADDRESS = "PAYMENT_SAVE_SHIPPING_ADDRESS";
export const PAYMENT_SAVE_PAYMENT_METHOD = "PAYMENT_SAVE_PAYMENT_METHOD";
